
import React from "react";
import { 
  Card, 
  CardContent, 
  CardDescription, 
  CardHeader, 
  CardTitle 
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FileText, BarChart, Download, PieChart, Clock, Users } from "lucide-react";

// Sample data for the reporting component
const reportsData = [
  { 
    id: "rep1", 
    name: "Monthly Headcount Report", 
    type: "Headcount", 
    frequency: "Monthly", 
    lastGenerated: "2024-04-30", 
    generatedBy: "Sarah Johnson",
    status: "complete"
  },
  { 
    id: "rep2", 
    name: "Quarterly Turnover Analysis", 
    type: "Turnover", 
    frequency: "Quarterly", 
    lastGenerated: "2024-03-31", 
    generatedBy: "John Smith",
    status: "complete"
  },
  { 
    id: "rep3", 
    name: "Annual Compensation Review", 
    type: "Compensation", 
    frequency: "Annual", 
    lastGenerated: "2023-12-15", 
    generatedBy: "Michael Brown",
    status: "complete"
  },
  { 
    id: "rep4", 
    name: "Recruitment Pipeline Report", 
    type: "Recruitment", 
    frequency: "Weekly", 
    lastGenerated: "2024-05-05", 
    generatedBy: "Lisa Wong",
    status: "pending"
  },
];

export const HRReporting = () => {
  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div className="flex items-center gap-2">
          <BarChart className="h-5 w-5 text-primary" />
          <h2 className="text-2xl font-bold">HR Reporting & Analytics</h2>
        </div>
        
        <div className="flex flex-col md:flex-row gap-2 w-full md:w-auto">
          <Button className="flex gap-1">
            <FileText className="h-4 w-4" />
            Generate New Report
          </Button>
          <Button variant="outline" className="flex gap-1">
            <Download className="h-4 w-4" />
            Export Data
          </Button>
        </div>
      </div>

      <Tabs defaultValue="reports" className="w-full">
        <TabsList className="mb-4">
          <TabsTrigger value="reports">Standard Reports</TabsTrigger>
          <TabsTrigger value="custom">Custom Reports</TabsTrigger>
          <TabsTrigger value="analytics">Analytics Dashboard</TabsTrigger>
        </TabsList>

        <TabsContent value="reports" className="space-y-4">
          <Card>
            <CardHeader>
              <div className="flex flex-col md:flex-row justify-between items-start md:items-center">
                <div>
                  <CardTitle>Available Reports</CardTitle>
                  <CardDescription>
                    Standard HR reports that can be generated and exported
                  </CardDescription>
                </div>

                <div className="flex flex-col md:flex-row gap-2 w-full md:w-auto mt-4 md:mt-0">
                  <Select defaultValue="all">
                    <SelectTrigger className="w-full md:w-40">
                      <SelectValue placeholder="Report Type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Types</SelectItem>
                      <SelectItem value="headcount">Headcount</SelectItem>
                      <SelectItem value="turnover">Turnover</SelectItem>
                      <SelectItem value="recruitment">Recruitment</SelectItem>
                      <SelectItem value="compensation">Compensation</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Report Name</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Frequency</TableHead>
                    <TableHead>Last Generated</TableHead>
                    <TableHead>Generated By</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {reportsData.map((report) => (
                    <TableRow key={report.id}>
                      <TableCell className="font-medium">{report.name}</TableCell>
                      <TableCell>{report.type}</TableCell>
                      <TableCell>{report.frequency}</TableCell>
                      <TableCell>{report.lastGenerated}</TableCell>
                      <TableCell>{report.generatedBy}</TableCell>
                      <TableCell>
                        <Badge 
                          className={report.status === "complete" 
                            ? "bg-green-100 text-green-800" 
                            : "bg-amber-100 text-amber-800"
                          }
                        >
                          {report.status}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-right">
                        <Button variant="ghost" size="sm" className="mr-1">View</Button>
                        <Button variant="ghost" size="sm">
                          <Download className="h-4 w-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="custom" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Custom Report Builder</CardTitle>
              <CardDescription>
                Create customized reports by selecting specific data points and parameters
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-center h-48">
                <p className="text-muted-foreground">Custom report builder will be displayed here</p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="analytics" className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium flex items-center">
                  <Users className="h-4 w-4 mr-2 text-primary" />
                  Employee Headcount
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">152</div>
                <p className="text-xs text-muted-foreground">+3.2% from last month</p>
                <div className="h-[120px] mt-4 flex items-center justify-center">
                  <PieChart className="h-16 w-16 text-muted-foreground" />
                </div>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium flex items-center">
                  <Clock className="h-4 w-4 mr-2 text-primary" />
                  Average Tenure
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">3.7 years</div>
                <p className="text-xs text-muted-foreground">+0.3 years from last year</p>
                <div className="h-[120px] mt-4 flex items-center justify-center">
                  <BarChart className="h-16 w-16 text-muted-foreground" />
                </div>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium flex items-center">
                  <Users className="h-4 w-4 mr-2 text-primary" />
                  Turnover Rate
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">8.2%</div>
                <p className="text-xs text-muted-foreground">-1.5% from last quarter</p>
                <div className="h-[120px] mt-4 flex items-center justify-center">
                  <BarChart className="h-16 w-16 text-muted-foreground" />
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default HRReporting;
