
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive:
          "bg-destructive text-destructive-foreground hover:bg-destructive/90",
        outline:
          "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-10 px-4 py-2",
        sm: "h-9 rounded-md px-3",
        lg: "h-11 rounded-md px-8",
        icon: "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
  downloadPdf?: boolean
  printable?: boolean
  documentTitle?: string
  documentContent?: () => string | React.ReactNode
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, downloadPdf, printable, documentTitle, documentContent, onClick, children, ...props }, ref) => {
    const Comp = asChild ? Slot : "button"
    
    const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
      // Process original onClick handler if provided
      if (onClick) {
        onClick(e);
      }
      
      // Handle PDF download functionality
      if (downloadPdf && documentContent) {
        const title = documentTitle || "document";
        const content = typeof documentContent === 'function' ? documentContent() : '';
        
        const printWindow = window.open('', '_blank');
        if (printWindow) {
          printWindow.document.write(`
            <html>
              <head>
                <title>${title}</title>
                <style>
                  body { font-family: Arial, sans-serif; padding: 20px; }
                  h1 { color: #333; }
                  table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                  th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                  th { background-color: #f2f2f2; }
                  @media print {
                    button { display: none; }
                  }
                </style>
              </head>
              <body>
                ${content}
                <div style="margin-top: 30px; text-align: center; color: #666; font-size: 12px;">
                  <p>Generated by Pulse Point CX | ${new Date().toLocaleString()}</p>
                </div>
                <div style="text-align: center; margin-top: 20px;">
                  <button onclick="window.print()">Print Document</button>
                </div>
              </body>
            </html>
          `);
          printWindow.document.close();
          
          // Auto-trigger download as PDF using browser print to PDF functionality
          if (!printable) {
            setTimeout(() => {
              printWindow.print();
            }, 500);
          }
        }
      }
      
      // Handle print-only functionality
      if (printable && !downloadPdf && documentContent) {
        const title = documentTitle || "document";
        const content = typeof documentContent === 'function' ? documentContent() : '';
        
        const printWindow = window.open('', '_blank');
        if (printWindow) {
          printWindow.document.write(`
            <html>
              <head>
                <title>${title}</title>
                <style>
                  body { font-family: Arial, sans-serif; padding: 20px; }
                  h1 { color: #333; }
                  table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                  th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                  th { background-color: #f2f2f2; }
                  @media print {
                    button { display: none; }
                  }
                </style>
              </head>
              <body>
                ${content}
                <div style="margin-top: 30px; text-align: center; color: #666; font-size: 12px;">
                  <p>Generated by Pulse Point CX | ${new Date().toLocaleString()}</p>
                </div>
                <div style="text-align: center; margin-top: 20px;">
                  <button onclick="window.print()">Print Document</button>
                </div>
              </body>
            </html>
          `);
          printWindow.document.close();
          setTimeout(() => {
            printWindow.focus();
          }, 300);
        }
      }
    }
    
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        onClick={handleClick}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }
